title: Declan Kneita
logo: /assets/images/profile.jfif

theme: jekyll-theme-minimal

description: >
  Aspiring Engineer with a focus on Artificial Intelligence, Machine Learning, and Data Science.

  <br><strong>Contact:</strong><br>
  <a href="mailto:declankneita2025@u.northwestern.edu">Email</a><br>
  <a href="https://linkedin.com/in/declan-kneita" target="_blank">LinkedIn</a><br>
  <a href="https://github.com/dk1414" target="_blank">GitHub</a><br>
  <a href="https://medium.com/@declankneita" target="_blank">Medium Blog</a>
